/*
 * Copyright (c) 2022 - 2025, The casual project. All rights reserved.
 *
 * This software is licensed under the MIT license, https://opensource.org/licenses/MIT
 */
//-*- coding: utf-8 -*-
plugins {
    id 'java-library'
    id 'groovy'
}

dependencies{
    compileOnly libs.javaee_api
    compileOnly libs.casual_api
    compileOnly libs.casual_caller_api
    compileOnly libs.casual_inbound_handler_api
    compileOnly libs.casual_fielded_annotations

    //implementation libs.casual_api_spi_impl
    implementation libs.gson

    //for test
    testImplementation libs.casual_api

    // for spock
    testImplementation platform(libs.groovy_bom)
    testImplementation libs.groovy
    testImplementation platform(libs.spock_bom)
    testImplementation libs.spock_core
    testImplementation libs.byte_buddy
}
